### ISSUE TITLE
Konwersja liczebnikow

### ISSUE THREAD

**Issue by savary** [kawu/parseme-pl-2020#10]
Dostrzeglam moj blad w tabeli konwersji, w ktorej jest:

```
numcol:pl:acc:m1:rec    NUM    Animacy=Hum|Case=Acc|Gender=Masc|Number=Plur|NumForm=Word|NumType=Sets
...
num:pl:inst:n:congr    NUM    Case=Ins|Gender=Neut|Number=Plur|NumForm=Digit
...
```

Otoz cecha NumForm zalezy od tego jak pisze się dany liczebnki, np.
```
dwa    ... NumForm=Word
2   ... NumForm=Digit
```
Widze, ze w wynikach konwersji wyglada to na zrobione poprawnie. To znaczy, ze wziales pod uwage te regule w swoich skryptach, prawda?

Pozostaja tokeny zlepione z liter i cyfr:
```
Bytomianinnapisał21     ... NumForm=Digit
54Grudziądzdzisiaj  ... NumForm=Word
```
Mysle, ze dla nich kazdy wybor jest dobry.
Mozna by sie jedynie zstanawiac nad ulamkami:
`1/2    ... NumForm=Word`
Powinny one raczej miec wartosc NumForm=Digit. Ale nie sadze, by z tego powodu trzeba bylo konwertowac od nowa caly korpus.

**Comment by kawu** [comment]
Skrypt (niestety) traktuje tą tabelę konwersji dosłownie i nie bierze pod uwagę form.  W pliku `NKJP.cupt` znajdziesz np. następujący, niepoprawny wpis:

```
...       7       NUM     numcol:pl:nom:n:rec     Case=Nom|Gender=Neut|Number=Plur|NumForm=Word|NumType=Sets     ...
```

Więc możemy to jeszcze poprawić.  Jak myślisz?

**Comment by savary** [comment]
Jeśli jest czas, to oczywiście tak.

**Comment by savary** [comment]
Jeszcze recznie poprawiłam dwie linie (Word-->Digit):

**750 000**	750000	NUM	num:pl:gen:m2:congr	Animacy=Nhum|Case=Gen|Gender=Masc|Number=Plur|NumForm=**Word**|NumType=Card	5	nummod	_	_	*

**40 270**	40270	NUM	num:pl:acc:m3:rec	Animacy=Inan|Case=Acc|Gender=Masc|Number=Plur|NumForm=**Word**|NumType=Card	12	nummod:gov	_	_	*

Commit pchniety. Ostatnia wersja w parseme_corpus_pl/not_to_release/after-update-to-ud-2

**Comment by kawu** [comment]
Świetnie.  Zamykam wątek.
