### ISSUE TITLE
Za malo linii i jednostek w plikach

### ISSUE THREAD

**Issue by savary** [kawu/parseme-pl-2020#8]
Najnowszy korpsu przeslany przez Ciebie mailem ma mniej linii i jednostek niz pliki po consistency checks:
```
[savary@dib-0314px][~/shared-task-pl/Aktualizacja-starych-plikow/2020-03-06-od-Kuby]$ ls
NKJP.cupt  parseme-pl-conv-v0.4.zip  PCC.cupt  PDB.cupt
[savary@dib-0314px][~/shared-task-pl/Aktualizacja-starych-plikow/2020-03-06-od-Kuby]$ cat *.cupt | wc -l
328032
[savary@dib-0314px][~/shared-task-pl/Aktualizacja-starych-plikow/2020-03-06-od-Kuby]$ cat *.cupt | grep -E '(VID)|(LVC)|(IRV)' | wc -l
5061
```
```
[savary@dib-0314px][~/shared-task/Gitlab/parseme_corpus_pl/not_to_release/after-consistency-checks]$ ls
120.cupt    130-3.cupt  310.cupt  PCC.cupt                        pl-pdb-ud-dev-NEWS.cupt   pl-pdb-ud-test-110-200-320.cupt  pl-pdb-ud-test-OTHER.cupt         pl-pdb-ud-train-NEWS.cupt
130-2.cupt  130-5.cupt  330.cupt  pl-pdb-ud-dev-110-200-320.cupt  pl-pdb-ud-dev-OTHER.cupt  pl-pdb-ud-test-NEWS.cupt         pl-pdb-ud-train-110-200-320.cupt  pl-pdb-ud-train-OTHER.cupt
[savary@dib-0314px][~/shared-task/Gitlab/parseme_corpus_pl/not_to_release/after-consistency-checks]$ cat *.cupt | wc -l
493210
[savary@dib-0314px][~/shared-task/Gitlab/parseme_corpus_pl/not_to_release/after-consistency-checks]$ cat *.cupt | grep -E '(VID)|(LVC)|(IRV)' | wc -l
7703

```

**Comment by kawu** [comment]
W korpusie który przesłałem są wyłącznie zdania który były już zaanotowane w poprzedniej edycji.  Tak więc nie ma tam plików `pl-pdb-ud-*-NEWS.cupt`, `pl-pdb-ud-*-OTHER.cupt`, ani `pl-pdb-ud-*-110-200-320.cupt`.  Tak jak napisałem w jednym z ostatnich maili, założyłem że tych nie trzeba (czy wręcz nie należy) przetwarzać, ponieważ one już bazują na najnowszym PDB-UD.

Nie jestem też pewien co do sposobu w który liczysz liczbę jednostek, ponieważ znaczniki VID, LVC, IRV pojawiają się też czasem w metadanych.

**Comment by kawu** [comment]
U mnie liczba jednostek się zgadza (przy zignorowaniu metadanych).  Po consistency checks:
```
.../not_to_release/after-consistency-checks$ cat 1* 3* PCC.cupt | grep -E '(:VID)|(:LVC)|(:IRV)' | wc -l
4806
```

W nowych danych:
```
$ cat *.cupt | grep -E '(:VID)|(:LVC)|(:IRV)' | wc -l
4806
```

Natomiast skrypt wydaje się usuwać wielokrotne pola "metadata" w metadanych.  Po consistency checks:
```
.../not_to_release/after-consistency-checks$ cat 1* 3* PCC.cupt | grep -E '(# metadata)' | wc -l
591
```

W nowych danych:
```
$ cat *.cupt | grep -E '(# metadata)' | wc -l
579
```

**Comment by kawu** [comment]
A czy w .conllu, w metadanych, dozwolona jest dowolna liczba linii z tym samym kluczem (tak jak u nas, wiele linii `# metadata = X`, gdzie `X` może się różnić)?  Bo jeśli tak, to problem jest w bibliotece z której korzystam (https://github.com/EmilStenstrom/conllu), która najwyraźniej zakłada że może być tylko jedna linia metadanych z takim samym kluczem (a jak jest ich wiele, to tylko jedna zostaje zachowana).

**Comment by savary** [comment]
Potwierdzam, œe ilość zaanotowanych jednostek (nie biorac pod uwage plikow nowo zaanotowanych: pl-pdb-ud-*-110-200-320.cupt, pl-pdb-ud-*-OTHER.cupt, pl-pdb-ud-*-NEWS.cupt) się zgadza.

**Comment by savary** [comment]
Nie mam informacji na temat matadnych w Conllu. Ale my i tak publikujemy korpus bez komentarzy # metadata. Sa one wylacznie do wewnetrznego uzytku (sprawdzanie kosystencji).

**Comment by savary** [comment]
Jeszcze rzuce okiem na niektore etykiety morfoskladniowe.

**Comment by savary** [comment]
Twoja konwersja wygląda na poprawną. Wielkie dzieki!

**Comment by kawu** [comment]
Świetnie, no to zamykam wątek.
