### ISSUE TITLE
Czyszczenie metadanych i NotMWE

### ISSUE THREAD

**Issue by savary** [kawu/parseme-pl-2020#9]
Zaladowalam najswiezsza wersje calosci do  parseme_corpus_pl/not_to_release/after-update-to-ud-2.5.

Trzy ostatnie sprawy to:

- usuniecie metadanych sluzacych do poprawy konsystencji
- usuniecie anotacji z etykieta NotMWE 
- sprawdzenie jeszcze raz poprawnosci formatu .cupt

Wydaje mi sie, ze jakies skrypty w utilities/ wykonuja te 2 pierwsze zadania. Wiesz cos na ten temat?

**Comment by kawu** [comment]
Zdaje się, że skrypt [`to_cupt.py`](https://gitlab.com/parseme/corpora/-/wikis/parseme-tools#file-format-conversion) potrafi to zrobić.  Ale jeszcze nie sprawdzałem.

Co do trzeciego punktu, masz jakieś konkretne pomysły jak sprawdzić poprawność formatu .cupt?

**Comment by savary** [comment]
Tak, robi to skrypt  [validate_cupt.py](https://gitlab.com/parseme/sharedtask-data/-/blob/master/1.1/bin/validate_cupt.py).

**Comment by kawu** [comment]
Zamykam wątek: etykiety NotMWE zostały już usunięte (a jeśli jeszcze jakieś zostały, to i tak będą usuwane później w ramach podziału na train/test), a czyszczenie metadanych już jest zaimplementowane w skrypcie dzielącym na train/test.
